//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WashingHouseChetvernyaDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filial()
        {
            this.Machine = new HashSet<Machine>();
        }
    
        public int idFilial { get; set; }
        public string Title { get; set; }
        public Nullable<int> FilStaff1 { get; set; }
        public Nullable<int> FilStaff2 { get; set; }
        public Nullable<int> Admin { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machine { get; set; }
    }
}
