//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WashingHouseChetvernyaDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wash
    {
        public int idWash { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> WashPowder { get; set; }
        public Nullable<int> WashMachine { get; set; }
        public Nullable<int> WashStuff { get; set; }
        public Nullable<int> WashStatus { get; set; }
        public Nullable<bool> Drying { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> TypePayment { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Powder Powder { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StatusWash StatusWash { get; set; }
    }
}
